image: registry.gitlab.com/fdroid/ci-images-client:latest

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

stages:
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=$PWD/.gradle
  - export ANDROID_COMPILE_SDK=`sed -n 's,.*compileSdkVersion\s*\([0-9][0-9]*\).*,\1,p' libnetcipher/build.gradle`
  - alias sdkmanager="sdkmanager --no_https"
  - echo y | sdkmanager
      "platforms;android-${ANDROID_COMPILE_SDK}"
      "$(sed -nE 's,.*buildToolsVersion *.([0-9.]+).*,build-tools;\1,p' libnetcipher/build.gradle)"
      "build-tools;23.0.3" > /dev/null

.test-template: &test-template
  artifacts:
    name: "${CI_PROJECT_PATH}_${CI_JOB_STAGE}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}"
    paths:
      - "logcat.txt"
      - "*/build/reports"
      - "*/build/outputs/*ml"
      - "*/build/outputs/apk"
    expire_in: 1 week
    when: on_failure
  after_script:
    - echo "Download debug artifacts from https://gitlab.com/${CI_PROJECT_PATH}/-/jobs"

# Run the most important first. Then we can decide whether to ignore
# the style tests if the rest of the more meaningful tests pass.
test:
  stage: test
  <<: *test-template
  script:
    # print lint errors/warnings to build log
    - sed -i 's,\s*textReport .*,\ttextReport true,g' */build.gradle
    # 'assemble' everything and run all checks that do not require a device/emulator
    - ./gradlew build -PdisablePreDex
    # test release process
    - ./gradlew jarRelease -PdisablePreDex

errorprone:
  stage: test
  script:
    - for f in */build.gradle; do cat tools/errorprone.gradle >> $f; done
    - ./gradlew assembleDebug -PdisablePreDex

.connected-template: &connected-template
  retry: 2
  script:
    - ./gradlew assembleDebug
    - export AVD_SDK=`echo $CI_JOB_NAME | awk '{print $2}'`
    - export AVD_TAG=`echo $CI_JOB_NAME | awk '{print $3}'`
    - export AVD_ARCH=`echo $CI_JOB_NAME | awk '{print $4}'`
    - export AVD_PACKAGE="system-images;android-${AVD_SDK};${AVD_TAG};${AVD_ARCH}"
    - echo $AVD_PACKAGE
    - emulator -accel-check || true
    - alias sdkmanager
    - echo y | sdkmanager "emulator" "platforms;android-$AVD_SDK" > /dev/null
    - if ! avdmanager list avd | grep "Name. avd$AVD_SDK$"; then
          set -x;
          rm -rf ~/.android/avd  $ANDROID_HOME/system-images;
          echo y | sdkmanager "$AVD_PACKAGE" > /dev/null;
          echo no | avdmanager create avd --name avd$AVD_SDK --tag "$AVD_TAG" --package "$AVD_PACKAGE" --device "Nexus 5";
          export RAMSIZE="$((`sed -n 's,^MemAvailable:[^0-9]*\([0-9][0-9]*\)[^0-9]*$,\1,p' /proc/meminfo` * 3 / 4 / 1024))";
          sed -i '/^hw\.ramSize\s*=.*/d' ~/.android/avd/*.avd/config.ini;
          echo "hw.ramSize=$RAMSIZE" >> ~/.android/avd/*.avd/config.ini;
          avdmanager list avd;
          set +x;
      fi
    - adb start-server
    - ls -l ~/.android
    - emulator -avd avd$AVD_SDK
        -no-audio
        -no-jni
        -no-snapstorage
        -no-window
        -skip-adb-auth
        -verbose
        -wipe-data
        &
    - wait-for-emulator
    - adb devices
    - adb shell input keyevent 82 &
    - ./gradlew connectedCheck || (adb -e logcat -d > logcat.txt; exit 1)

connected 22 default armeabi-v7a:
  <<: *test-template
  <<: *connected-template

.kvm-template: &kvm-template
  tags:
    - fdroid
    - kvm
  <<: *test-template
  <<: *connected-template

connected 17 default x86:
  <<: *kvm-template

connected 18 default x86:
  <<: *kvm-template
  only:
    - master@guardianproject/netcipher

connected 21 default x86:
  <<: *kvm-template
  only:
    - master@guardianproject/netcipher

connected 22 default x86:
  <<: *kvm-template
  only:
    - master@guardianproject/netcipher

connected 25 default x86:
  <<: *kvm-template

connected 26 google_apis x86:
  <<: *kvm-template
  only:
    - master@guardianproject/netcipher

connected 27 google_apis_playstore x86:
  <<: *kvm-template
  only:
    - master@guardianproject/netcipher

connected 28 default x86_64:
  <<: *kvm-template


after_script:
    # this file changes every time but should not be cached
    - rm -f $GRADLE_USER_HOME/caches/modules-2/modules-2.lock
    - rm -fr $GRADLE_USER_HOME/caches/*/plugin-resolution/
